- name: Instalando Apache e PHP
  hosts: all
  tasks:
  - name: Instalando no Ubuntu
    apt:
     name: "{{ item }}"
     state: present
    with_items:
    - "apache2"
    - "php7.0"
    when: ansible_distribution == "Ubuntu"
  - name: Instalando no centOS
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - "httpd"
    - "php"
    when: ansible_distribution == "CentOS"
  - name: Copiando o index.php
    copy:
      src: /etc/ansible/index.php
      dest: /var/www/html/index.php
  - name: Iniciando no Ubuntu
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"
  - name: Iniciando no CentOS
    service:
      name: httpd 
      state: started
    when: ansible_distribution == "CentOS"
