- name: Playbook para instalar nginx
  hosts: all 
  tasks: 
  - name: Instalando no Ubuntu
    become: yes
    apt: name=nginx state=absent update_cache=yes
    notify: nginx
    when: ansible_distribution == "Ubuntu"
  - name: Instalando epel no centOS
    become: yes
    yum:
      name: epel-release
      state: absent
      update_cache: yes
    when: ansible_distribution == "centOS"
  - name: Instalando nginx no centOS
    become: yes
    yum:
      name: nginx
      state: absent
      update_cache: yes
    notify: nginx
    when: ansible_distribution == "centOS"
  - name: Instalando cowsay
    become: yes 
    package:
      name: cowsay
      state: absent
  - name: Garantindo /etc/hosts
    become: yes
    lineinfile:
      dest: /etc/hosts
      create: yes
      line: "{{ item }}"
    with_items:
      - "192.168.99.10 devops"
      - "192.168.99.20 docker"
      - "192.168.99.30 automation"
  handlers: 
   - name: nginx
     service: 
       name: nginx
       state: restarted   
